trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

name: $(Date:yyyy.MM.dd).$(Rev:r)

variables:
  azureServiceConnection: 'sw-development-connection'
  resourceGroupName: 'webauthn-test'
  location: 'eastus'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy WebAuthn-Test Infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureServiceConnection)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    csmFile: './main.bicep'
    deploymentMode: 'Incremental'
    deploymentName: webauthn-test-$(Build.BuildNumber)